name: App test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Depedancies
       run: |
        npm ci
      - name: Run Test
       run: |
        npm test