name: App test
on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Depedancies
        run: npm ci
      - name: Run Test
        run: npm test
        env:
          DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL}}
          JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          CRYPTO_SECRET: ${{secrets.CRYPTO_SECRET}}
